### ISSUE TITLE
Support for SP112SU

### ISSUE THREAD

**Issue by Laezor** [ghagl/Gurich#3]
Hello there I have SP112SU printer which should be the same as SP112 but is also a scanner

I did follow the compile instructions and I can say this

- the status command works
- printing the testpage of the printer works
- using the actual printing command fails after preparing the pages. I tried the example ps file and pdf file

INFO: Preparing page 1
INFO: Preparing page 2
INFO: Preparing page 3
INFO: Preparing page 4
INFO: Preparing page 5
INFO: Preparing page 6
INFO: Preparing page 7
INFO: Preparing page 8
INFO: Preparing page 9
INFO: Preparing page 10
libusb: error [submit_bulk_transfer] submiturb failed, errno=16
libusb: error [submit_bulk_transfer] submiturb failed, errno=16
libusb: error [submit_bulk_transfer] submiturb failed, errno=16

**Comment by ghagl** [comment]
Hi!

I suspect that this model is slightly different. Either, try to use this driver as a CUPS filter, or do a USB packet dump. I have an incomplete draft describing the process of reverse engineering available here:

https://gustafhaglund.se/blog/gurich.html

You wouldn't need to do any actual reverse engineering though, only provide a USB dump from Wireshark.

In short, what you need to do is to get a Windows VM, install Ricoh's driver, and then use usbmon and Wireshark in Linux to dump the relevant USB packets. I officially recommend Microsoft's official Windows VM images which are available free of charge for testing purposes.

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

From this Wireshark dump I would be able to add support for this printer. I think it's going to be a few lines in order to add support, so nothing major.

**Comment by Laezor** [comment]
I saw now the reply sorry for the waiting. I've been busy! I am guessing this is what you need for the capture just to be clear? 

![image](https://github.com/ghagl/Gurich/assets/32393101/dbc758cc-3e15-44d6-bb11-3781dab22c84)

**Comment by ghagl** [comment]
Yes, you can export all entries as a separate dump file (pcap) and attach it here. Please note that scanning support is most probably a bigger undertaking than just the printing, unless it's already supported by libsane, and for now I'm only going to look at implementing support for printing.

**Comment by Laezor** [comment]
Okay I am attaching it, had to zip it up since it doesnt let that format to upload here. We can take a look for scanning another time, as long as printing can work I am fine. Thank you for taking a look!

[printer capture ricoh.zip](https://github.com/ghagl/Gurich/files/14001647/printer.capture.ricoh.zip)

**Comment by ghagl** [comment]
I think this might help:
```diff -u --recursive Gurich/src/prntcommon.c Gurich2/src/prntcommon.c
--- Gurich/src/prntcommon.c	2024-01-23 21:55:56.894669102 +0100
+++ Gurich2/src/prntcommon.c	2024-01-23 21:54:40.059089756 +0100
@@ -88,10 +88,10 @@
 
 	while (totSize != 0)
 	{
-		unsigned char tBuf[4096];
+		unsigned char tBuf[65536];
 
-		if (totSize > 4096)
-			tsSize = 4096;
+		if (totSize > 65536)
+			tsSize = 65536;
 		else
 			tsSize = totSize;
 
```

I won't be able to test this personally and the only difference I am aware of is the buffer size. Please apply this patch and test whether it works.

**Comment by Laezor** [comment]
I am assuming I change these values in the file prntcommon.c and then I use make all command again right?

Well after doing these changes. I am still getting the same error as before. 

libusb: error [submit_bulk_transfer] submiturb failed, errno=16

**Comment by ghagl** [comment]
You might already have thought about this, but are you certain that cups or anything else isn't able to interfere?

You should preferably not have cups, libsane or anything else that might try to talk to the printer running at the same time when you try out printing via Gurich. errno=16 is in Linux equivalent to EBUSY, device or resource being busy, and I assume libusb uses standard Linux errno here.

Due to this printer also having scanning, it's possible that it exists several different interfaces on USB level that needs configuration. https://stackoverflow.com/questions/44122912/libusb-error-submit-bulk-transfer-submiturb-failed-error-1-errno-2-what-am

In the latter case, different USB interfaces, I would recommend to take a look with PyUSB and lsusb similarly to what's being described there.

**Comment by Laezor** [comment]
- Having cups disabled at the moment, same error even if its enabled
- i dont think have libsane installed ? I am not sure to be honest.
- I havent used anything to scan yet since I want printing to work first.

I used lsusb and pyusb so I can attach the files here if you wish to see them. Since you know more than me, let me know if you can figure out something. 
[ricoh_pyusb.txt](https://github.com/ghagl/Gurich/files/14067220/ricoh_pyusb.txt)
[ricoh_lsusb.txt](https://github.com/ghagl/Gurich/files/14067223/ricoh_lsusb.txt)

**Comment by ghagl** [comment]
Please try out this patch:

```
--- Gurich/src/basic.c	2024-02-05 13:42:01.639116580 +0100
+++ Gurich2/src/basic.c	2024-02-05 13:43:08.628598838 +0100
@@ -45,14 +45,14 @@
 
 	g->device = libusb_get_device(g->device_handle);
 
-	libusb_error = libusb_kernel_driver_active(g->device_handle, 0);
+	libusb_error = libusb_kernel_driver_active(g->device_handle, 1);
 	if (libusb_error == 1) {
-		if ((libusb_error = libusb_detach_kernel_driver(g->device_handle, 0)) < 0) {
+		if ((libusb_error = libusb_detach_kernel_driver(g->device_handle, 1)) < 0) {
 			goto libusb_fail;
 		}
 	}
 
-	libusb_error = libusb_claim_interface(g->device_handle, 0);
+	libusb_error = libusb_claim_interface(g->device_handle, 1);
 	if (libusb_error != 0) {
 		goto libusb_fail;
 	}
@@ -122,8 +122,8 @@
 {
 	if (g->initialized)
 	{
-		libusb_release_interface(g->device_handle, 0);
-		libusb_attach_kernel_driver(g->device_handle, 0);
+		libusb_release_interface(g->device_handle, 1);
+		libusb_attach_kernel_driver(g->device_handle, 1);
 		libusb_close(g->device_handle);
 
 		libusb_exit(g->ctx);
 ```

According to your USB testing output your printer has its printing interface on `#1`, in contrast to the SP112 one which resides on `#0`. Interface `#0` on the SP112SU seems to be for scanning, at least what I would suspect.

**Comment by Laezor** [comment]
After applying this patch the previous error is now history!

INFO: Preparing page 1
INFO: Preparing page 2
INFO: Preparing page 3
INFO: Preparing page 4
INFO: Preparing page 5
INFO: Preparing page 6
INFO: Preparing page 7
INFO: Preparing page 8
INFO: Preparing page 9
INFO: Preparing page 10

this is the output but printing is not happening. I see the blue LED on the printer blinking and nothing else happens, So I am guessing its stuck at reading the pages?

**Comment by ghagl** [comment]
While I might have an idea, I would like to have some data. If you are able to, please attempt to print the document with Gurich, and then Ricoh's driver in the VM, with separate USB packet dumps. To be noted though is that you don't need to print the GPL (as provided in this repo), so long as you print the exact same document in both instances (well, to make it an apple to apple comparison).

**Comment by Laezor** [comment]
[printer capture.zip](https://github.com/ghagl/Gurich/files/14230455/printer.capture.zip)

I captured both gurich and with the Ricoh driver. Seems like the ricoh one has less packets than the gurich one. I am attaching the file.

**Comment by ghagl** [comment]
Please apply this patch:
```
--- Gurich/src/shworkaround.c	2024-01-23 21:55:56.894669102 +0100
+++ Gurich2/src/shworkaround.c	2024-02-11 07:07:46.245892591 +0100
@@ -32,18 +32,20 @@
 		res = "1200x600";
 	}
 
-	for (size_t i = 0; papertype[i] != '\0'; i++){
-		papertype[i] = tolower(papertype[i]);
+	char * gs_papertype = malloc(strlen(papertype)+1);
+	gurich_alloc_check(gs_papertype);
+	strcpy(gs_papertype, papertype);
+	for (size_t i = 0; gs_papertype[i] != '\0'; i++){
+		gs_papertype[i] = tolower(gs_papertype[i]);
 	}
 
 	snprintf(
 		gs_cmd,
 		250,
-		"/usr/bin/gs -sDEVICE=pbmraw -sOutputFile=%s%%03d-page.pbm "
+		"/usr/bin/env gs -sDEVICE=pbmraw -sOutputFile=%s%%03d-page.pbm "
 		"-r%s -dQUIET -dBATCH -dNOPAUSE -sPAPERSIZE=%s %s",
 		GURICH_TEMP_DIR,
 		res,
-		papertype,
+		gs_papertype,
 		psfile
 	);
 
@@ -54,4 +56,6 @@
 	#endif
 
 	system(gs_cmd);
+
+	free(gs_papertype);
 }
--- Gurich/src/prnt.c	2024-01-23 21:55:56.893669095 +0100
+++ Gurich2/src/prnt.c	2024-02-11 07:13:23.311097649 +0100
@@ -63,7 +63,7 @@
 	tme = localtime(&t);
 	strftime(datetime, sizeof(datetime), "%Y/%m/%d %H:%M:%S", tme);
 
-	sendbunker.data = malloc((beginlen = (100 + strlen(psfile))));
+	sendbunker.data = malloc((beginlen = (161 + strlen(username) + strlen(psfile))));
 	fs.files = malloc(10);
 
 	gurich_alloc_check(sendbunker.data);
```

**Comment by Laezor** [comment]
After applying this patch I am getting this error.

```

Unknown paper size: (%s).
Error: /undefinedfilename in --findlibfile--
Operand stack:   (%s%03d-page.pbm)
Execution stack:   %interp_exit   .runexec2   --nostringval--   findlibfile   --nostringval--   2   %stopped_push   --nostringval--   findlibfile   findlibfile   false   1   %stopped_push   findlibfile   1813   1   3   %oparray_pop   findlibfile
Dictionary stack:   --dict:743/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--
Current allocation mode is local
GPL Ghostscript 10.02.1: Unrecoverable error, exit code 1
```

**Comment by ghagl** [comment]
As a quick fix you can probably revert the changes in shworkaround.c, as it's only prnt.c that should matter. The changes there are only to make sure that it's A4 and not a4 that gets sent to the printer, but I am not sure whether this actually matters in the end.

Save this to a new file named oopsie.patch and do `patch -p1 -R < oopsie.patch`
```
--- Gurich/src/shworkaround.c	2024-01-23 21:55:56.894669102 +0100
+++ Gurich2/src/shworkaround.c	2024-02-11 07:07:46.245892591 +0100
@@ -32,18 +32,20 @@
 		res = "1200x600";
 	}
 
-	for (size_t i = 0; papertype[i] != '\0'; i++){
-		papertype[i] = tolower(papertype[i]);
+	char * gs_papertype = malloc(strlen(papertype)+1);
+	gurich_alloc_check(gs_papertype);
+	strcpy(gs_papertype, papertype);
+	for (size_t i = 0; gs_papertype[i] != '\0'; i++){
+		gs_papertype[i] = tolower(gs_papertype[i]);
 	}
 
 	snprintf(
 		gs_cmd,
 		250,
-		"/usr/bin/gs -sDEVICE=pbmraw -sOutputFile=%s%%03d-page.pbm "
+		"/usr/bin/env gs -sDEVICE=pbmraw -sOutputFile=%s%%03d-page.pbm "
 		"-r%s -dQUIET -dBATCH -dNOPAUSE -sPAPERSIZE=%s %s",
 		GURICH_TEMP_DIR,
 		res,
-		papertype,
+		gs_papertype,
 		psfile
 	);
 
@@ -54,4 +56,6 @@
 	#endif
 
 	system(gs_cmd);
+
+	free(gs_papertype);
 }
```

**Comment by Laezor** [comment]
I tried to do the patch method but it did get an error malformed patch line 28. But never mind I edited the lines back manually.

Printing is working!! I tried the pdf I used for wireshark and the gplv3.ps! Thank you! Does this mean I can add it now to cups ?

**Comment by ghagl** [comment]
Nice! :grinning: 
Proper support for SP112SU and corresponding bugfix (the patches here) will probably get merged into a release sometime soon.

It was years ago I last tested the code for integration with CUPS, so I am not aware how well that works with current CUPS. There is rudimentary CUPS filter support, very plain and basic, and not really tested in practice. With some patience and willingness to edit things you could probably get it working though. That is however something that should be tracked in another issue than this one.

**Comment by gustafhaglund** [comment]
This got addressed in a new release today, but not tested on my end.
